apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-jenkins-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-jenkins-example
  template:
    metadata:
      labels:
        app: python-jenkins-example
    spec:
      containers:
      - name: python-jenkins-example
        image: mayurpatil1211/python-jenkins:24
        ports:
        - name: http-port
          containerPort: 80
        resources:
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: python-jenkins-example
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: http-port
    protocol: TCP
  selector:
    app: python-jenkins-example
  type: NodePort
